/* 
 Generated By GameBoyPngConverter

 Tiles data

 Number of Tiles   : 200
*/
#ifndef __SplashScreenTiles_h_INCLUDE
#define __SplashScreenTiles_h_INCLUDE

/* Bank of tiles. */
#define SplashScreenTilesBank 0
/* Start of tile array. */
extern const unsigned char SplashScreenTiles[];

#endif
