/*

 CREDITSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\cozzi\Documents\gbdk\games\mine\assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __CreditsMap_h_INCLUDE
#define __CreditsMap_h_INCLUDE

#define CreditsMapWidth 20
#define CreditsMapHeight 18
#define CreditsMapBank 0

extern const unsigned char CreditsMap[];

#endif

/* End of CREDITSMAP.H */
