/*

 LOSEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 1
   Tile set      : C:\Users\cozzi\Documents\gbdk\GBTD_GBMB_release\GBMB\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LoseMapWidth 5
#define LoseMapHeight 1
#define LoseMapBank 0

const unsigned char LoseMap[] =
{
  0x19,0x1C,0x20,0x12,0x33
};

/* End of LOSEMAP.C */
