/*

 LOSEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 1
   Tile set      : \assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __LoseMap_h_INCLUDE
#define __LoseMap_h_INCLUDE

#define LoseMapWidth 5
#define LoseMapHeight 1
#define LoseMapBank 0

extern const unsigned char LoseMap[];

#endif

/* End of LOSEMAP.H */
