/*

 MENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : \assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __MenuMap_h_INCLUDE
#define __MenuMap_h_INCLUDE

#define MenuMapWidth 20
#define MenuMapHeight 18
#define MenuMapBank 0

extern const unsigned char MenuMap[];

#endif

/* End of MENUMAP.H */
