/*

 MINEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : \assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __MineMap_h_INCLUDE
#define __MineMap_h_INCLUDE

#define MineMapWidth 20
#define MineMapHeight 18
#define MineMapBank 0

extern const unsigned char MineMap[];

#endif

/* End of MINEMAP.H */
