/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 20 x 18
*/
#ifndef __SplashScreenMap_h_INCLUDE
#define __SplashScreenMap_h_INCLUDE

#define SplashScreenMapWidth 20
#define SplashScreenMapHeight 18
#define SplashScreenMapBank 0

extern const unsigned char SplashScreenMap[];

#endif
