/*

 WINDOWMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\cozzi\Documents\gbdk\games\mine\assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WindowMapWidth 20
#define WindowMapHeight 1
#define WindowMapBank 0

const unsigned char WindowMap[] =
{
  0x3A,0x1D,0x0E,0x22,0x20,0x12,0x3A,0x0C,0x0C,0x0C,
  0x0C,0x0C,0x1A,0x16,0x1B,0x12,0x20,0x3C,0x0C,0x0C
};

/* End of WINDOWMAP.C */
