/*

 WINDOWMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\cozzi\Documents\gbdk\games\mine\assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __WindowMap_h_INCLUDE
#define __WindowMap_h_INCLUDE

#define WindowMapWidth 20
#define WindowMapHeight 1
#define WindowMapBank 0

extern const unsigned char WindowMap[];

#endif

/* End of WINDOWMAP.H */
