/*

 WINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 1
   Tile set      : \assets\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __WinMap_h_INCLUDE
#define __WinMap_h_INCLUDE

#define WinMapWidth 4
#define WinMapHeight 1
#define WinMapBank 0

extern const unsigned char WinMap[];

#endif

/* End of WINMAP.H */
