/*

 WINMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 1
   Tile set      : C:\Users\cozzi\Documents\gbdk\GBTD_GBMB_release\GBMB\tiles\MineTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WinMapWidth 4
#define WinMapHeight 1
#define WinMapBank 0

const unsigned char WinMap[] =
{
  0x24,0x16,0x1B,0x33
};

/* End of WINMAP.C */
